# Exo1

In [1]:
import numpy as np 

In [2]:
#1
A=np.arange(0,100,3)
print(A)
#2
B=np.sin((A**2)*(np.pi/2))
print(B)
#3
C=np.max(B)
print(C)
#4
D=np.sum(B == C)
print (D)

[ 0  3  6  9 12 15 18 21 24 27 30 33 36 39 42 45 48 51 54 57 60 63 66 69
 72 75 78 81 84 87 90 93 96 99]
[ 0.00000000e+00  1.00000000e+00 -2.20436424e-15  1.00000000e+00
 -8.81745695e-15  1.00000000e+00 -4.11555602e-14  1.00000000e+00
 -3.52698278e-14  1.00000000e+00 -7.64253880e-14  1.00000000e+00
 -1.64622241e-13  1.00000000e+00 -1.86173549e-13  1.00000000e+00
 -1.41079311e-13  1.00000000e+00 -4.84086880e-13  1.00000000e+00
 -3.05701552e-13  1.00000000e+00 -6.06706795e-14  1.00000000e+00
 -6.58488964e-13  1.00000000e+00 -1.18966170e-12  1.00000000e+00
 -7.44694194e-13  1.00000000e+00 -1.14257584e-12  1.00000000e+00
 -5.64317245e-13  1.00000000e+00]
1.0
17


# Exo 2

In [3]:
import numpy as np
M = np.array([[1,0,0],[0,2,0],[0,0,3]])
n,p=M.shape
print(M)

#1
def est_diagonale(M):
    if n!= p:
        return False
    for i in range (n):
        for j in range (p):
            if i!=j and M[i,j ]!= 0:
                return False
    return True
print(est_diagonale(M))

#2
def est_triangulaire_sup(M):
    if n!= p:
        return False
    for i in range (n):
        for j in range (i):
            if M[i,j ]!= 0:
                return False
    return True
print(est_triangulaire_sup(M))

[[1 0 0]
 [0 2 0]
 [0 0 3]]
True
True


# Exo 3

In [4]:
#Construction 1 avec boucles
E=np.ones((8,8), dtype=int)  
for i in range(8):
    for j in range(8):
         E[i,j]= 1
E[0:-1,1:-1] = 0
print(E)
#Construction 2
F = np.ones((8,8), dtype=int)
F[0:-1,1:-1] = 0
print(F)
#Construction 3
G = np.tile([[1,1],[1,1]], (4,4))
G[0:-1,1:-1] = 0
print(G)
#Construction 4 bonus
H = np.ones((8,4), dtype=int)
I = np.ones((8,4), dtype=int)
J = np.concatenate((H, I), axis=1)
J[0:-1,1:-1] = 0
print(J)

[[1 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 1]
 [1 1 1 1 1 1 1 1]]
[[1 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 1]
 [1 1 1 1 1 1 1 1]]
[[1 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 1]
 [1 1 1 1 1 1 1 1]]
[[1 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 1]
 [1 1 1 1 1 1 1 1]]


# Exo4

In [5]:
#n=10 au lieu de n=1000000 
#1
n=10
s=0
for i in range (0,n+1):
    s=s+i
    print(s)
#2
import time
print(time.clock())

0
1
3
6
10
15
21
28
36
45
55
49.997756297


C:\Users\Dell\Anaconda3\lib\site-packages\ipykernel_launcher.py:10: DeprecationWarning: time.clock has been deprecated in Python 3.3 and will be removed from Python 3.8: use time.perf_counter or time.process_time instead
  # Remove the CWD from sys.path while we load stuff.


In [6]:
#3
b = np.arange(11)
print(b)
c=np.sum(b)
print(c)
#4
print(time.clock())

[ 0  1  2  3  4  5  6  7  8  9 10]
55
57.790706563


C:\Users\Dell\Anaconda3\lib\site-packages\ipykernel_launcher.py:7: DeprecationWarning: time.clock has been deprecated in Python 3.3 and will be removed from Python 3.8: use time.perf_counter or time.process_time instead
  import sys


# Exo5

In [7]:
#1
K=np.random.rand(50,50)
print(K)
#2 Solution non trouvée

[[0.7295222  0.9716776  0.04743609 ... 0.51837709 0.88814172 0.35050192]
 [0.82875081 0.52690463 0.40994075 ... 0.88709347 0.15523372 0.26237218]
 [0.45109622 0.05098799 0.60107345 ... 0.36228057 0.47829376 0.14198369]
 ...
 [0.39759    0.59756585 0.22118528 ... 0.86288874 0.99777508 0.17675771]
 [0.57322139 0.72884795 0.48264676 ... 0.68426329 0.17156178 0.43151854]
 [0.34102675 0.71197065 0.17706649 ... 0.09799674 0.46069018 0.15554835]]


# Exo6

In [8]:
import numpy as np
#1
K=np.random.rand(50,50)
print(K)

[[0.76553551 0.3492302  0.03713511 ... 0.34726442 0.81271312 0.50595227]
 [0.03598744 0.94205926 0.93446778 ... 0.54477285 0.68111487 0.93281003]
 [0.58210583 0.23628721 0.94132719 ... 0.13327422 0.68765567 0.17620778]
 ...
 [0.3130036  0.53112954 0.62369267 ... 0.84990346 0.27772447 0.23581089]
 [0.94358316 0.24623524 0.62026179 ... 0.17769348 0.38738524 0.4654455 ]
 [0.53220114 0.48498248 0.53416724 ... 0.95791344 0.76597256 0.51778605]]


In [9]:
#2
f= (K<0.5)
print(f) #Les valeurs inférieurs à 0.5 prennent True

[[False  True  True ...  True False False]
 [ True False False ... False False False]
 [False  True False ...  True False  True]
 ...
 [ True False False ... False  True  True]
 [False  True False ...  True  True  True]
 [False  True False ... False False False]]


In [10]:
g=np.sum(f)
print(g) #On comptabilise le nombre de True, correspondant au nombre des valeurs inférieures à 0.5

1245


In [11]:
#3
h=f.astype(int)
print(h) #Par défaut les True prennent des 1 et les False des 0

[[0 1 1 ... 1 0 0]
 [1 0 0 ... 0 0 0]
 [0 1 0 ... 1 0 1]
 ...
 [1 0 0 ... 0 1 1]
 [0 1 0 ... 1 1 1]
 [0 1 0 ... 0 0 0]]


In [12]:
ff=(K>0.5)
hh=ff.astype(int)
print(hh) #Les valeurs inférieures à 0.5 (True) prennent 0 et les autres (False) des 1

[[1 0 0 ... 0 1 1]
 [0 1 1 ... 1 1 1]
 [1 0 1 ... 0 1 0]
 ...
 [0 1 1 ... 1 0 0]
 [1 0 1 ... 0 0 0]
 [1 0 1 ... 1 1 1]]


# Exo7

In [13]:
#1
a=np.array([[1,2,1,1],[0,1,2,1],[1,0,1,2],[2,1,0,1]]).reshape(4,4)
print(a)
np.linalg.det(a) #Déterminant de a != 0  ===> Il n'y a donc qu'une solution à ce système

[[1 2 1 1]
 [0 1 2 1]
 [1 0 1 2]
 [2 1 0 1]]


-4.0

In [14]:
#2 solution
b=np.array([0,0,1,0]).reshape(4,1)
x=np.linalg.solve(a,b) 
print(x)

[[-0.5]
 [ 0. ]
 [-0.5]
 [ 1. ]]


In [15]:
#3: vérification du résultat en utilisant un produit matriciel
c=a.dot(x)
print(c)

[[0.]
 [0.]
 [1.]
 [0.]]


In [16]:
#3
np.allclose(np.dot(a, x), b) #vérification 2 du résultat

True

# Exo 8

In [17]:
from itertools import groupby
def RLEcompress(tab):
    return [(len(list(g)),k) for k,g in groupby (tab)]
RLEcompress("AAAAAACCCCAABAAAAAADDDD")

[(6, 'A'), (4, 'C'), (2, 'A'), (1, 'B'), (6, 'A'), (4, 'D')]

In [18]:
def RLEuncompress(list):
    return ''.join(c * n for n,c in list)
RLEuncompress([(6, 'A'), (4, 'C'), (2, 'A'), (1, 'B'), (6, 'A'), (4, 'D')])

'AAAAAACCCCAABAAAAAADDDD'